### ISSUE TITLE
various_syntax.vdmppの実行でエラーを吐きました

### ISSUE THREAD

**Issue by Morichan** [HirokiTachiyama/BWDM#13]
```java:エラー文
$ java -jar BWDM.jar various_syntax.vdmpp
Exception in thread "main" java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2541)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:873)
	at java.base/java.lang.System.loadLibrary(System.java:1857)
	at com.microsoft.z3.Native.<clinit>(Native.java:14)
	at com.microsoft.z3.Context.<init>(Context.java:41)
	at bwdm.symbolicExecutionUnit.SymbolicExecutioner.<init>(SymbolicExecutioner.java:32)
	at bwdm.symbolicExecutionUnit.SeUnitMain.<init>(SeUnitMain.java:13)
	at bwdm.BwdmMain.exeBWDM(BwdmMain.java:177)
	at bwdm.BwdmMain.main(BwdmMain.java:20)
exit status 1
```

バージョンはJava9を利用しています。

**Comment by korosuke613** [comment]
z3をインストールしてください。
参考: [Hello SMT-Solver by z3
](https://qiita.com/tachiyama/items/2c1dae78ff8104a2b327)

**Comment by HirokiTachiyama** [comment]
VDMの構文自体に未対応であることが問題ですorz
参考リンクが僕の記事なんですねぇ…たまげたなぁ
